// Code generated by counterfeiter. DO NOT EDIT.
package handlersfakes

import (
	"context"
	"sync"

	"github.com/ivan1993spb/snake-bot/internal/http/handlers"
)

type FakeAppGetState struct {
	GetStateStub        func(context.Context) map[int]int
	getStateMutex       sync.RWMutex
	getStateArgsForCall []struct {
		arg1 context.Context
	}
	getStateReturns struct {
		result1 map[int]int
	}
	getStateReturnsOnCall map[int]struct {
		result1 map[int]int
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeAppGetState) GetState(arg1 context.Context) map[int]int {
	fake.getStateMutex.Lock()
	ret, specificReturn := fake.getStateReturnsOnCall[len(fake.getStateArgsForCall)]
	fake.getStateArgsForCall = append(fake.getStateArgsForCall, struct {
		arg1 context.Context
	}{arg1})
	stub := fake.GetStateStub
	fakeReturns := fake.getStateReturns
	fake.recordInvocation("GetState", []interface{}{arg1})
	fake.getStateMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeAppGetState) GetStateCallCount() int {
	fake.getStateMutex.RLock()
	defer fake.getStateMutex.RUnlock()
	return len(fake.getStateArgsForCall)
}

func (fake *FakeAppGetState) GetStateCalls(stub func(context.Context) map[int]int) {
	fake.getStateMutex.Lock()
	defer fake.getStateMutex.Unlock()
	fake.GetStateStub = stub
}

func (fake *FakeAppGetState) GetStateArgsForCall(i int) context.Context {
	fake.getStateMutex.RLock()
	defer fake.getStateMutex.RUnlock()
	argsForCall := fake.getStateArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeAppGetState) GetStateReturns(result1 map[int]int) {
	fake.getStateMutex.Lock()
	defer fake.getStateMutex.Unlock()
	fake.GetStateStub = nil
	fake.getStateReturns = struct {
		result1 map[int]int
	}{result1}
}

func (fake *FakeAppGetState) GetStateReturnsOnCall(i int, result1 map[int]int) {
	fake.getStateMutex.Lock()
	defer fake.getStateMutex.Unlock()
	fake.GetStateStub = nil
	if fake.getStateReturnsOnCall == nil {
		fake.getStateReturnsOnCall = make(map[int]struct {
			result1 map[int]int
		})
	}
	fake.getStateReturnsOnCall[i] = struct {
		result1 map[int]int
	}{result1}
}

func (fake *FakeAppGetState) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.getStateMutex.RLock()
	defer fake.getStateMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeAppGetState) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ handlers.AppGetState = new(FakeAppGetState)
