name: Go

on: push

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.21.5

    - name: Go Mod
      run: go mod download

    - name: Go Format
      run: gofmt -s -w . && git diff --exit-code

    - name: Go Tidy
      run: go mod tidy && git diff --exit-code

    - name: Go Vet
      run: go vet

    - name: golangci-lint
      uses: golangci/golangci-lint-action@v3
      with:
        version: v1.55.2

    - name: Go staticcheck
      uses: dominikh/staticcheck-action@v1.2.0
      with:
        version: "2023.1"
        install-go: false

    - name: Go Build
      run: go build -v ./...

    - name: Go Test
      run: go test -race -shuffle=on -coverprofile=coverage.txt -v -cover ./...

    # TODO: Add test coverage.
