on: push
name: Validate OpenAPI specification
jobs:
  validate:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: swagger-validator
      uses: mbowman100/swagger-validator-action@master
      with:
        files: api/openapi.yaml
